// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: protos/posttag.proto

package posttag

import (
	post "github.com/Forum-service/Forum-api-gateway/genproto/post"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostTag message definition (Represents the relationship between posts and tags)
type PostTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId    string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // UUID
	TagId     string `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`    // UUID
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *PostTag) Reset() {
	*x = PostTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTag) ProtoMessage() {}

func (x *PostTag) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTag.ProtoReflect.Descriptor instead.
func (*PostTag) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{0}
}

func (x *PostTag) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostTag) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *PostTag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Request for creating a new post-tag relationship
type CreatePostTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TagId  string `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *CreatePostTagRequest) Reset() {
	*x = CreatePostTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostTagRequest) ProtoMessage() {}

func (x *CreatePostTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostTagRequest.ProtoReflect.Descriptor instead.
func (*CreatePostTagRequest) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostTagRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreatePostTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

// Response after creating a new post-tag relationship
type CreatePostTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostTag *PostTag `protobuf:"bytes,1,opt,name=post_tag,json=postTag,proto3" json:"post_tag,omitempty"`
}

func (x *CreatePostTagResponse) Reset() {
	*x = CreatePostTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostTagResponse) ProtoMessage() {}

func (x *CreatePostTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostTagResponse.ProtoReflect.Descriptor instead.
func (*CreatePostTagResponse) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostTagResponse) GetPostTag() *PostTag {
	if x != nil {
		return x.PostTag
	}
	return nil
}

// Request for deleting a post-tag relationship
type DeletePostTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TagId  string `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *DeletePostTagRequest) Reset() {
	*x = DeletePostTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostTagRequest) ProtoMessage() {}

func (x *DeletePostTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostTagRequest.ProtoReflect.Descriptor instead.
func (*DeletePostTagRequest) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePostTagRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeletePostTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

// Response after deleting a post-tag relationship
type DeletePostTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeletePostTagResponse) Reset() {
	*x = DeletePostTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostTagResponse) ProtoMessage() {}

func (x *DeletePostTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostTagResponse.ProtoReflect.Descriptor instead.
func (*DeletePostTagResponse) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePostTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for getting all post-tag relationships
type GetAllPostTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional filters
	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TagId  string `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	// Pagination
	Page  int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetAllPostTagsRequest) Reset() {
	*x = GetAllPostTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPostTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostTagsRequest) ProtoMessage() {}

func (x *GetAllPostTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostTagsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPostTagsRequest) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllPostTagsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetAllPostTagsRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *GetAllPostTagsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllPostTagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response containing a list of post-tag relationships
type GetAllPostTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostTags []*PostTag `protobuf:"bytes,1,rep,name=post_tags,json=postTags,proto3" json:"post_tags,omitempty"`
}

func (x *GetAllPostTagsResponse) Reset() {
	*x = GetAllPostTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPostTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostTagsResponse) ProtoMessage() {}

func (x *GetAllPostTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostTagsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostTagsResponse) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllPostTagsResponse) GetPostTags() []*PostTag {
	if x != nil {
		return x.PostTags
	}
	return nil
}

type GetPostsByTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId string `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"` // UUID of the tag
	// Pagination
	Page  int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`   // Default to 1
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // Default to 10
}

func (x *GetPostsByTagRequest) Reset() {
	*x = GetPostsByTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostsByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByTagRequest) ProtoMessage() {}

func (x *GetPostsByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByTagRequest.ProtoReflect.Descriptor instead.
func (*GetPostsByTagRequest) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostsByTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *GetPostsByTagRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostsByTagRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPostsByTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*post.Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"` // Array of post
}

func (x *GetPostsByTagResponse) Reset() {
	*x = GetPostsByTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_posttag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostsByTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByTagResponse) ProtoMessage() {}

func (x *GetPostsByTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_posttag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByTagResponse.ProtoReflect.Descriptor instead.
func (*GetPostsByTagResponse) Descriptor() ([]byte, []int) {
	return file_protos_posttag_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostsByTagResponse) GetPosts() []*post.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_protos_posttag_proto protoreflect.FileDescriptor

var file_protos_posttag_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x74, 0x61, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x1a, 0x12, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x58, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61,
	0x67, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x07,
	0x70, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x22, 0x46, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22,
	0x31, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x71, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x45, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50,
	0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x54,
	0x61, 0x67, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x22, 0x57, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x73, 0x74,
	0x73, 0x32, 0xc3, 0x02, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x2e, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61,
	0x67, 0x12, 0x1b, 0x2e, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x2e,
	0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6f, 0x72,
	0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x2e, 0x66, 0x6f, 0x72,
	0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x6f, 0x72, 0x75, 0x6d,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x70, 0x6f, 0x73, 0x74,
	0x74, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_posttag_proto_rawDescOnce sync.Once
	file_protos_posttag_proto_rawDescData = file_protos_posttag_proto_rawDesc
)

func file_protos_posttag_proto_rawDescGZIP() []byte {
	file_protos_posttag_proto_rawDescOnce.Do(func() {
		file_protos_posttag_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_posttag_proto_rawDescData)
	})
	return file_protos_posttag_proto_rawDescData
}

var file_protos_posttag_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_posttag_proto_goTypes = []any{
	(*PostTag)(nil),                // 0: forum.PostTag
	(*CreatePostTagRequest)(nil),   // 1: forum.CreatePostTagRequest
	(*CreatePostTagResponse)(nil),  // 2: forum.CreatePostTagResponse
	(*DeletePostTagRequest)(nil),   // 3: forum.DeletePostTagRequest
	(*DeletePostTagResponse)(nil),  // 4: forum.DeletePostTagResponse
	(*GetAllPostTagsRequest)(nil),  // 5: forum.GetAllPostTagsRequest
	(*GetAllPostTagsResponse)(nil), // 6: forum.GetAllPostTagsResponse
	(*GetPostsByTagRequest)(nil),   // 7: forum.GetPostsByTagRequest
	(*GetPostsByTagResponse)(nil),  // 8: forum.GetPostsByTagResponse
	(*post.Post)(nil),              // 9: forum.Post
}
var file_protos_posttag_proto_depIdxs = []int32{
	0, // 0: forum.CreatePostTagResponse.post_tag:type_name -> forum.PostTag
	0, // 1: forum.GetAllPostTagsResponse.post_tags:type_name -> forum.PostTag
	9, // 2: forum.GetPostsByTagResponse.posts:type_name -> forum.Post
	1, // 3: forum.PostTagService.CreatePostTag:input_type -> forum.CreatePostTagRequest
	3, // 4: forum.PostTagService.DeletePostTag:input_type -> forum.DeletePostTagRequest
	7, // 5: forum.PostTagService.GetPostsByTag:input_type -> forum.GetPostsByTagRequest
	5, // 6: forum.PostTagService.GetAllPostTags:input_type -> forum.GetAllPostTagsRequest
	2, // 7: forum.PostTagService.CreatePostTag:output_type -> forum.CreatePostTagResponse
	4, // 8: forum.PostTagService.DeletePostTag:output_type -> forum.DeletePostTagResponse
	8, // 9: forum.PostTagService.GetPostsByTag:output_type -> forum.GetPostsByTagResponse
	6, // 10: forum.PostTagService.GetAllPostTags:output_type -> forum.GetAllPostTagsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_posttag_proto_init() }
func file_protos_posttag_proto_init() {
	if File_protos_posttag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_posttag_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PostTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePostTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePostTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePostTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePostTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllPostTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllPostTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetPostsByTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_posttag_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetPostsByTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_posttag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_posttag_proto_goTypes,
		DependencyIndexes: file_protos_posttag_proto_depIdxs,
		MessageInfos:      file_protos_posttag_proto_msgTypes,
	}.Build()
	File_protos_posttag_proto = out.File
	file_protos_posttag_proto_rawDesc = nil
	file_protos_posttag_proto_goTypes = nil
	file_protos_posttag_proto_depIdxs = nil
}
